env:
  global:
    - secure: EdDFhvUGbG10dN2ePjLXPJSuFC8QwkwsnKCkJ4Yy6TfRwcdGCFK2C91oCCgMfOTqhkNDlOgLAfRz8LD0S7bytafUu5g9gtRjVVS1IjTPQhZyVpB6tki91fNEdAQD/6MU7dFhTSaat4MzBlqyhbTTE0ewP2Fank0imtH+hzLb7Y4=
    - LD_LIBRARY_PATH=/usr/local/lib
before_install:
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - yes | sudo add-apt-repository ppa:ricotz/testing
  - sudo apt-get update
install:
  - sudo apt-get install cargo
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
  - sudo apt-get install gtk+3.0 libgtk-3-dev
script:
  - rustc --version
  - pkg-config --modversion gtk+-3.0
  - ./configure
  - make GTK_VERSION=GTK_3_6
  - rustdoc -o doc src/rgtk.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh