[options]
girs_dir = "gir-files"
library = "GLib"
version = "2.0"
min_cfg_version = "2.32"
target_path = "."
work_mode = "normal"

generate = [
    "GLib.FormatSizeFlags",
    "GLib.KeyFileError",
    "GLib.KeyFileFlags",
]

ignore = [
]

manual = [
    "GLib.Bytes",
    "GLib.Error",
    "GLib.Variant",
    "GLib.VariantType",
    "GLib.UserDirectory",
    "GObject.Object",
]

[[object]]
name = "GLib.*"
status = "generate"
    [[object.function]]
    name = "propagate_error"
    #empty first parameter
    ignore = true
    [[object.function]]
    name = "set_error_literal"
    #empty first parameter
    ignore = true
    [[object.function]]
    pattern = "atomic_.+"
    ignore = true
    [[object.function]]
    pattern = "bit_.*lock"
    ignore = true
    [[object.function]]
    name = "get_filename_charsets"
    #string
    ignore = true
    [[object.function]]
    pattern = "str.+v"
    #string
    ignore = true
    [[object.function]]
    name = "strv_length"
    #string
    ignore = true
    [[object.function]]
    pattern = "ucs4_to_utf.+"
    ignore = true
    [[object.function]]
    pattern = "unichar_.*compose"
    ignore = true
    [[object.function]]
    name = "unichar_get_mirror_char"
    ignore = true
    [[object.function]]
    name = "unix_open_pipe"
    ignore = true
    [[object.function]]
    name = "utf16_to_ucs4"
    ignore = true
    [[object.function]]
    name = "utf16_to_utf8"
    ignore = true
    [[object.function]]
    name = "utf8_to_ucs4"
    ignore = true
    [[object.function]]
    name = "utf8_to_utf16"
    ignore = true
    [[object.function]]
    name = "utf8_to_ucs4_fast"
    ignore = true
    [[object.function]]
    name = "assertion_message_error"
    #Quark
    ignore = true
    [[object.function]]
    pattern = ".+_error_quark"
    #Quark
    ignore = true
    [[object.function]]
    pattern = "quark_.+_string"
    #Quark
    ignore = true
    [[object.function]]
    name = "spawn_close_pid"
    #Pid
    ignore = true
    [[object.function]]
    name = "get_current_dir"
    #manual
    ignore = true
    [[object.function]]
    pattern = "[gs]et_prgname"
    #manual pathbuf
    ignore = true
    [[object.function]]
    name = "get_user_name"
    #manual pathbuf is_windows_utf8
    ignore = true
    [[object.function]]
    pattern = "[gs]etenv"
    #manual is_windows_utf8
    ignore = true
    [[object.function]]
    name = "unsetenv"
    #manual is_windows_utf8
    ignore = true
    [[object.function]]
    name = "filename_to_uri"
    #manual is_windows_utf8
    ignore = true
    [[object.function]]
    name = "find_program_in_path"
    #manual is_windows_utf8
    ignore = true
    [[object.function]]
    name = "get_home_dir"
    #manual is_windows_utf8
    ignore = true
    [[object.function]]
    name = "get_real_name"
    #manual pathbuf? is_windows_utf8
    ignore = true
    [[object.function]]
    name = "get_tmp_dir"
    #manual is_windows_utf8
    ignore = true
    [[object.function]]
    name = "mkstemp"
    #manual is_windows_utf8
    ignore = true
    [[object.function]]
    name = "strdup"
    #not needed
    ignore = true
    [[object.function]]
    pattern = "unix_.+"
    cfg_condition = "unix"
    [[object.function]]
    name = "spawn_command_line_async"
    cfg_condition = "unix"
    [[object.function]]
    name = "convert_with_fallback"
    #out param not in .gir
    ignore = true
    [[object.function]]
    name = "unicode_canonical_decomposition"
    #out param not in .gir
    ignore = true
    [[object.function]]
    name = "unicode_canonical_ordering"
    #UCS-4 encoded string
    ignore = true
    [[object.function]]
    name = "ascii_strdown"
    #gsize
    ignore = true
    [[object.function]]
    name = "ascii_strup"
    #gsize
    ignore = true
    [[object.function]]
    name = "convert"
    #gsize
    ignore = true
    [[object.function]]
    name = "filename_to_utf8"
    #gsize
    ignore = true
    [[object.function]]
    name = "locale_from_utf8"
    #gsize
    ignore = true
    [[object.function]]
    name = "locale_to_utf8"
    #gsize
    ignore = true
    [[object.function]]
    name = "markup_escape_text"
    #gsize
    ignore = true
    [[object.function]]
    name = "strlcat"
    #gsize
    ignore = true
    [[object.function]]
    name = "strlcpy"
    #gsize
    ignore = true
    [[object.function]]
    name = "strndup"
    #gsize
    ignore = true
    [[object.function]]
    name = "strrstr_len"
    #gsize
    ignore = true
    [[object.function]]
    name = "strstr_len"
    #gsize
    ignore = true
    [[object.function]]
    name = "utf8_casefold"
    #gsize
    ignore = true
    [[object.function]]
    name = "utf8_collate_key"
    #gsize
    ignore = true
    [[object.function]]
    name = "utf8_collate_key_for_filename"
    #gsize
    ignore = true
    [[object.function]]
    name = "utf8_get_char_validated"
    #gsize
    ignore = true
    [[object.function]]
    name = "utf8_strchr"
    #gsize
    ignore = true
    [[object.function]]
    name = "utf8_strdown"
    #gsize
    ignore = true
    [[object.function]]
    name = "utf8_strlen"
    #gsize
    ignore = true
    [[object.function]]
    name = "utf8_strncpy"
    #gsize
    ignore = true
    [[object.function]]
    name = "utf8_strrchr"
    #gsize
    ignore = true
    [[object.function]]
    name = "utf8_strreverse"
    #gsize
    ignore = true
    [[object.function]]
    name = "utf8_strup"
    #gsize
    ignore = true

[[object]]
name = "GLib.KeyFile"
status = "generate"
       [[object.function]]
       name = "load_from_data_dirs"
       ignore = true
       [[object.function]]
       name = "load_from_dirs"
       ignore = true
       [[object.function]]
       name = "error_quark"
       ignore = true
       [[object.function]]
       name = "save_to_file"
       # file parameter needs to be a PathBuf
       ignore = true
       [[object.function]]
       name = "set_locale_string_list"
       #[&str] to *mut i8
       ignore = true
       [[object.function]]
       name = "set_string_list"
       #[&str] to *mut i8
       ignore = true
       [[object.function]]
       name = "load_from_data"
       #gsize
       ignore = true
