[options]
girs_dir = "gir-files"
library = "Gio"
version = "2.0"
min_cfg_version = "2.32"
target_path = "."
work_mode = "normal"

generate = [
    "Gio.Action",
    "Gio.ActionMap",
    "Gio.AppInfo",
    "Gio.ApplicationFlags",
    "Gio.Menu",
    "Gio.MenuAttributeIter",
    "Gio.MenuItem",
    "Gio.MenuLinkIter",
    "Gio.MenuModel",
    "Gio.Permission",
    "Gio.Resource",
    "Gio.ResourceError",
    "Gio.ResourceLookupFlags",
    "Gio.SettingsBindFlags",
    "Gio.SimpleActionGroup",
    "Gio.SimplePermission",
]

ignore = [
]

manual = [
    "GLib.Bytes",
    "GLib.Error",
    "GLib.Variant",
    "GLib.VariantType",
    "GObject.Object",
]

[[object]]
name = "Gio.ActionGroup"
status = "generate"
    [[object.function]]
    name = "query_action"
    ignore = true
    [[object.signal]]
    name = "action-state-changed"
    # ns
    ignore = true

[[object]]
name = "Gio.AppLaunchContext"
status = "generate"
    [[object.signal]]
    name = "launched"
    # ns
    ignore = true

[[object]]
name = "Gio.Application"
status = "generate"
trait = true

[[object]]
name = "Gio.Settings"
status = "generate"
    [[object.signal]]
    name = "writable-change-event"
    # missing Inhibit support
    ignore = true

[[object]]
name = "Gio.SimpleAction"
status = "generate"
    [[object.signal]]
    name = "activate"
    # ns
    ignore = true
    [[object.signal]]
    name = "change-state"
    # ns
    ignore = true
