[package]
name = "glib-sys"
version = "0.1.2"
authors = ["The Rust-GNOME Project Developers"]
build = "build.rs"
links = "glib"

description = "FFI bindings to GLib"
repository = "https://github.com/rust-gnome/glib"
license = "MIT"
homepage = "https://github.com/rust-gnome/glib"
documentation = "https://github.com/rust-gnome/glib"

keywords = ["glib", "ffi", "gtk", "gnome"]

[lib]
name = "glib_sys"

[dependencies]
libc = "0.1"

[build-dependencies]
pkg-config = "0.3"
