[package]
name = "glib-sys"
version = "0.1.0"
authors = [
    "guillaume1.gomez@gmail.com",
    "letang.jeremy@gmail.com",
    "mathijs.henquet@gmail.com",
    "bpgarman@fastmail.fm",
    "me@bstr.eu",
    "zsoakes@gmail.com",
    "Gleb Kozyrev <gleb@gkoz.com>",
]
build = "build.rs"
links = "glib"

description = "FFI bindings to GLib"
repository = "https://github.com/rust-gnome/glib"
license = "MIT"

[lib]
name = "glib_sys"

[dependencies]
libc = "0.1"

[build-dependencies]
pkg-config = "0.3"
