[package]
name = "cairo-sys-rs"
version = "0.3.0"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
links = "cairo"

description = "FFI bindings to libcairo"
repository = "https://github.com/gtk-rs/cairo"
license = "MIT"
homepage = "http://gtk-rs.org/"

keywords = ["cairo", "ffi", "gtk-rs", "gnome"]

[lib]
name = "cairo_sys"

[features]
"1.12" = []
"1.14" = ["1.12"]
"png" = []

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.7"
