[package]
name = "cairo-sys-rs"
version = "0.2.0"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
links = "cairo"

description = "FFI bindings to Cairo"
repository = "https://github.com/gtk-rs/cairo"
license = "MIT"
homepage = "https://github.com/gtk-rs/cairo"
documentation = "https://github.com/gtk-rs/cairo"

keywords = ["cairo", "ffi", "gtk", "gnome"]

[lib]
name = "cairo_sys"

[features]
"1.12" = []
"1.14" = ["1.12"]

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.5"
