[package]
authors = ["The Gtk-rs Project Developers"]
description = "FFI binding for libgdkx11"
homepage = "http://gtk-rs.org/"
keywords = ["gdkx11", "ffi", "gtk-rs", "gnome"]
license = "MIT"
repository = "https://github.com/gtk-rs/gtk-rs"
name = "gdkx11-sys"
version = "0.10.0"
build = "build.rs"
edition = "2018"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.gdk_x11_3_0]
name = "gdk-x11-3.0"
version = "3.14"

[package.metadata.system-deps.gdk_x11_3_0.feature-versions]
v3_16 = "3.16"
v3_24 = "3.24"
v3_24_2 = "3.24.2"

[lib]
name = "gdk_x11_sys"

[dependencies]
libc = "0.2"
x11 = "2.18"

[dependencies.gdk-sys]
path = "../../gdk/sys"

[dependencies.gdk-pixbuf-sys]
path = "../../gdk-pixbuf/sys"

[dependencies.gio-sys]
path = "../../gio/sys"

[dependencies.glib-sys]
path = "../../glib/sys"

[dependencies.gobject-sys]
path = "../../glib/gobject-sys"

[dependencies.pango-sys]
path = "../../pango/sys"

[dependencies.cairo]
package = "cairo-sys-rs"
path = "../../cairo/sys"
optional = true

[build-dependencies]
system-deps = "1.3"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v3_16 = []
v3_22 = ["v3_16"]
v3_24 = ["v3_22"]
v3_24_2 = ["v3_24", "cairo"]
dox = []
