on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.10
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.48.0"
    steps:
      - run: apt-get update -y
      - run: apt-get install -y libgtk-3-dev libglib2.0-dev libgraphene-1.0-dev git xvfb curl libcairo-gobject2 libcairo2-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      # atk
      # nightly
      - name: "atk: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path atk/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "atk-sys: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path atk/sys/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "atk: build nightly"
        run: cargo build --manifest-path atk/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      # not nightly
      - name: "atk: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path atk/Cargo.toml --features "v2_34"
        if: matrix.rust != 'nightly'
      - name: "atk-sys: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path atk/sys/Cargo.toml --features "v2_34"
        if: matrix.rust != 'nightly'
      - name: "atk: build"
        run: cargo build --manifest-path atk/Cargo.toml --features "v2_34"
        if: matrix.rust != 'nightly'
      # cairo
      - name: "cairo: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path cairo/Cargo.toml --features "png,pdf,svg,ps,use_glib,v1_16,freetype,script,xcb,xlib,win32-surface"
      - name: "cairo-sys: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path cairo/sys/Cargo.toml --features "png,pdf,svg,ps,use_glib,v1_16,freetype,script,xcb,xlib,win32-surface"
      - name: "cairo: build"
        run: cargo build --manifest-path cairo/Cargo.toml --features "png,pdf,svg,ps,use_glib,v1_16,freetype,script,xcb,xlib,win32-surface"
      # gdk
      - name: "gdk: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path gdk/Cargo.toml --features v3_24
      - name: "gdk: build nightly"
        run: cargo build --manifest-path gdk/Cargo.toml --features v3_24
      # gdk-pixbuf
      # nightly
      - name: "gdk-pixbuf: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path gdk-pixbuf/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "gdk-pixbuf-sys: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path gdk-pixbuf/sys/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "gdk-pixbuf: build nightly"
        run: cargo build --manifest-path gdk-pixbuf/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      # not nightly
      - name: "gdk-pixbuf: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path gdk-pixbuf/Cargo.toml --features "v2_40"
        if: matrix.rust != 'nightly'
      - name: "gdk-pixbuf-sys: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path gdk-pixbuf/sys/Cargo.toml --features "v2_40"
        if: matrix.rust != 'nightly'
      - name: "gdk-pixbuf: build"
        run: cargo build --manifest-path gdk-pixbuf/Cargo.toml --features "v2_40"
        if: matrix.rust != 'nightly'
      # gdkx11
      # nightly
      - name: "gdkx11: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path gdkx11/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "gdkx11-sys: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path gdkx11/sys/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "gdkx11: build nightly"
        run: cargo build --manifest-path gdkx11/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      # not nightly
      - name: "gdkx11: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path gdkx11/Cargo.toml --features "v3_24"
        if: matrix.rust != 'nightly'
      - name: "gdkx11-sys: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path gdkx11/sys/Cargo.toml --features "v3_24"
        if: matrix.rust != 'nightly'
      - name: "gdkx11: build"
        run: cargo build --manifest-path gdkx11/Cargo.toml --features "v3_24"
        if: matrix.rust != 'nightly'
      # gio
      # nightly
      - name: "gio: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path gio/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "gio: build nightly"
        run: cargo build --manifest-path gio/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      # not nightly
      - name: "gio: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path gio/Cargo.toml --features "v2_66"
        if: matrix.rust != 'nightly'
      - name: "gio: build"
        run: cargo build --manifest-path gio/Cargo.toml --features "v2_66"
        if: matrix.rust != 'nightly'
      # glib
      # nightly
      - name: "glib: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path glib/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "glib: build nightly"
        run: cargo build --manifest-path glib/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      #not nightly
      - name: "glib: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path glib/Cargo.toml --features "v2_66"
        if: matrix.rust != 'nightly'
      - name: "glib: build"
        run: cargo build --manifest-path glib/Cargo.toml --features "v2_66"
        if: matrix.rust != 'nightly'
      # glib-macros
      - name: "glib-macros: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path glib-macros/Cargo.toml
      - name: "glib-macros: build"
        run: cargo build --manifest-path glib-macros/Cargo.toml
      # graphene
      # nightly
      - name: "graphene: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path graphene/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "graphene: build nightly"
        run: cargo build --manifest-path graphene/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      # not nightly
      - name: "graphene: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path graphene/Cargo.toml --features "v1_10"
        if: matrix.rust != 'nightly'
      - name: "graphene: build"
        run: cargo build --manifest-path graphene/Cargo.toml --features "v1_10"
        if: matrix.rust != 'nightly'
      # gtk
      # nightly
      - name: "gtk: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path gtk/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "gtk: build nightly"
        run: cargo build --manifest-path gtk/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      # not nightly
      - name: "gtk: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path gtk/Cargo.toml --features "v3_24_9"
        if: matrix.rust != 'nightly'
      - name: "gtk: build"
        run: cargo build --manifest-path gtk/Cargo.toml --features "v3_24_9"
        if: matrix.rust != 'nightly'
      # pango
      # nightly
      - name: "pango: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path pango/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "pango: build nightly"
        run: cargo build --manifest-path pango/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      # not nightly
      - name: "pango: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path pango/Cargo.toml --features "v1_46"
        if: matrix.rust != 'nightly'
      - name: "pango: build"
        run: cargo build --manifest-path pango/Cargo.toml --features "v1_46"
        if: matrix.rust != 'nightly'
      # pangocairo
      # nightly
      - name: "pangocairo: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path pangocairo/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "pangocairo-sys: tests nightly"
        run: xvfb-run --auto-servernum cargo test --manifest-path pangocairo/sys/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      - name: "pangocairo: build nightly"
        run: cargo build --manifest-path pangocairo/Cargo.toml --all-features
        if: matrix.rust == 'nightly'
      # not nightly
      - name: "pangocairo: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path pangocairo/Cargo.toml
        if: matrix.rust != 'nightly'
      - name: "pangocairo-sys: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path pangocairo/sys/Cargo.toml
        if: matrix.rust != 'nightly'
      - name: "pangocairo: build"
        run: cargo build --manifest-path pangocairo/Cargo.toml
        if: matrix.rust != 'nightly'
      # examples
      - name: "examples"
        run: cargo build --manifest-path examples/Cargo.toml --bins --examples --all-features

      - uses: bcomnes/cleanup-xvfb@v1

  fmt:
    name: rust fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.10
    steps:
      - run: apt-get update -y
      - run: apt-get install -y libgtk-3-dev libglib2.0-dev libgraphene-1.0-dev git xvfb curl libcairo-gobject2 libcairo2-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings

  checker:
    name: gtk-rs checker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - atk
          - gdk
          - gdk-pixbuf
          - gdkx11
          - gio
          - glib
          - graphene
          - gtk
          - pango
          - pangocairo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: gtk-rs/checker
          ref: master
          path: checker
      - run: cargo build --release
        working-directory: checker
      - run: cargo run -- ../${{matrix.crate}}
        working-directory: checker
      - run: cargo run -- ../${{matrix.crate}}/sys
        working-directory: checker
      - run: ./check_init_asserts ../${{matrix.crate}}
        working-directory: checker
        if: matrix.crate == 'atk' || matrix.crate == 'gdk' || matrix.crate == 'gdkx11' || matrix.crate == 'gtk'
